site_name: Web estàtica amb mkdocs
docs_dir: "md"
site_dir: "docs"
dev_addr: localhost:4000
nav:
  - Introducció i  intal·lació: introduccio.md
  - Configuració: configuracio.md
  - Allotgem la web a Aules: aules.md
  - Allotgem la web a github: github.md
  - "Docència: Aules o github?": aules vs github.md

markdown_extensions:
  - admonition
  - attr_list

theme: material

plugins:
  - search
  - pdf-export
