site_name: Web estàtica amb mkdocs
docs_dir: 'md'
site_dir: 'docs'
dev_addr: localhost:4000
nav:
    - Home: index.md
    - Configuracio: configuracio.md
    - Allotgem la web a Aules: aules.md
    - Allotgem la web a github: github.md
    - Aules o github?: aules vs github.md 
    

markdown_extensions:
  - admonition
  - attr_list